### ISSUE TITLE
Does the project use a graph structure to describe interatomic distance information?

### ISSUE THREAD

**Issue by Littletoyone** [GRAPH-0/CDGS#2]
Thank you for your work, this project provides great results and inspiration!This work is based on discrete graph structures, so I'm curious, does this work then have information about distances between atoms using graph structures to describe them，Because I don't see it in the dataset.

**Comment by GRAPH-0** [comment]
Thanks for your interest. This work is based on 2D molecular graphs, where edges are defined by covalent bonds. The 3D coordinates of the atoms are not considered. Therefore distances between atoms are not used to construct the graph.

**Comment by Littletoyone** [comment]
Thank you for your answer, it was very useful for me. best wishes to you
